server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://192.168.231.129:3306/miaosha
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  redis:
    host: 192.168.231.129
    password: 123


mybatis:
  mapper-locations: classpath:/mapper/*.xml
