dubbo:
  application:
    name: center-web
  registry:
    protocol: zookeeper
    address: 192.168.231.129:2181

server:
  port: 9090

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.231.129
    port: 5672
    virtual-host: /yrg
    username: yrg
    password: 123

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.231.129:22122

image:
  server: http://192.168.231.129/